<?php
$this->headLink()
    ->prependStylesheet($this->basePath('assets/datatables/media/css/jquery.dataTables_themeroller.css'))
    ->prependStylesheet($this->basePath('assets/datatables/extras/TableTools/media/css/TableTools.css'))
//    ->prependStylesheet($this->basePath('assets/datatables/media/css/jquery.dataTables.min.css'))
    ->prependStylesheet($this->basePath('assets/jquery-ui/themes/humanity/theme.css'))
    ->prependStylesheet($this->basePath('assets/jquery-ui/themes/humanity/jquery-ui.min.css'));

$this->inlineScript()
    ->prependFile($this->basePath('assets/mot-reports/js/datatable.js'))
    ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/TableTools.js'))
    ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/ZeroClipboard.js'))
    ->prependFile($this->basePath('assets/datatables/media/js/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('assets/jquery-ui/jquery-ui.min.js'));

$this->inlineScript()->captureStart();
echo '
    $(function() {
        $( "#accordion" ).accordion();
    }); 
    ';
$this->inlineScript()->captureEnd();

?>

<div class="pageheader">
    <div class="col-md-5 pull-left">
        <div class="media">
            <div class="pageicon pull-left">
                <i class="fa fa-line-chart"></i>
            </div>
            <div class="media-body" style="padding-left: 5px">
                <ul class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->url('mot');?>">
                            <i class="glyphicon glyphicon-home"></i>
                        </a>
                    </li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Client</a></li>
                    <li>Payment Summary</li>
                </ul>
                <h4>Client Payment Summary</h4>
            </div>
        </div>
    </div>
    <!-- credit officer listing view helper-->
    <div class="col-md-5 pull-right">
        <form role="form" class="form-inline pull-right">
            <div class="form-group">
                <select class="form-control tooltips" 
                        data-placement="top" 
                        title="Select Branch">
                    <option>ALL</option>
                    <option>Iligan</option>
                    <option>Initao</option>
                    <option>Lugait</option>
                </select>
            </div>
            <div class="form-group">                    
                <select class="form-control tooltips" 
                        data-placement="top" 
                        title="Select Credit Officer">
                    <option>ALL</option>
                    <option>Mae Shiel Dio</option>
                </select>
            </div>
            <div class="form-group">
                <select class="form-control tooltips" 
                        data-placement="top" 
                        title="Select Year">
                    <option>2015</option>
                    <option>2014</option>
                    <option>2013</option>
                    <option>2012</option>
                </select>
            </div>
        </form>
    </div>
</div>
<div class="contentpanel">
    <div class="row-fluid">
        <div id="accordion">
            <?php echo "<h3>Summary</h3>"
            . "<div>" 
            . $this->DataTables(
                $this->result['name'],
                $this->result['header'],
                $this->result['data']
            ) 
            . "</div>"; ?>
        </div>
    </div>
</div>
