<?php
$this->headLink()
    ->prependStylesheet($this->basePath('assets/datatables/media/css/jquery.dataTables_themeroller.css'))
    ->prependStylesheet($this->basePath('assets/datatables/extras/TableTools/media/css/TableTools.css'))
//    ->prependStylesheet($this->basePath('assets/datatables/media/css/jquery.dataTables.min.css'))
    ->prependStylesheet($this->basePath('assets/jquery-ui/themes/humanity/theme.css'))
    ->prependStylesheet($this->basePath('assets/jquery-ui/themes/humanity/jquery-ui.min.css'));

$this->inlineScript()
    ->prependFile($this->basePath('assets/mot-reports/js/datatable.js'))
    ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/TableTools.js'))
    ->prependFile($this->basePath('assets/datatables/extras/TableTools/media/js/ZeroClipboard.js'))
    ->prependFile($this->basePath('assets/datatables/media/js/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('assets/jquery-ui/jquery-ui.min.js'));

$this->inlineScript()->captureStart();
echo '
    $(function() {
        $( "#accordion" ).accordion();
    }); 
    ';

echo '
    $(function() {
        $( "#from" ).datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 1,
          onClose: function( selectedDate ) {
            $( "#to" ).datepicker( "option", "minDate", selectedDate );
          }
        });
        $( "#to" ).datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 1,
          onClose: function( selectedDate ) {
            $( "#from" ).datepicker( "option", "maxDate", selectedDate );
          }
        });
    });
    ';
$this->inlineScript()->captureEnd();

?>

<div class="pageheader">
    <div class="col-md-4 pull-left">
        <div class="media">
            <div class="pageicon pull-left">
                <i class="fa fa-line-chart"></i>
            </div>
            <div class="media-body" style="padding-left: 5px">
                <ul class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->url('mot');?>"><i class="glyphicon glyphicon-home"></i></a>
                    </li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Transactions</a></li>
                    <li>Teller Transactions</li>
                </ul>
                <h4>Teller Transactions</h4>
            </div>
        </div>
    </div>
    <!-- credit officer listing view helper-->
    <div class="col-md-8 pull-right">
        <form role="form" class="form-inline pull-right">
            <div class="form-group">
                <select class="form-control tooltips" 
                        data-placement="top" 
                        title="Select Branch">
                    <option>ALL</option>
                    <option>Iligan</option>
                    <option>Initao</option>
                    <option>Lugait</option>
                </select>
            </div>
            <div class="form-group">                    
                <select class="form-control tooltips" 
                        data-placement="top" 
                        title="Select Credit Officer">
                    <option>ALL</option>
                    <option>Mae Shiel Dio</option>
                </select>
            </div>
            <div class="form-group">
                <input type="text" id="from" name="from" 
                       placeholder="Select Date FROM">
                <input type="text" id="to" name="to" 
                       placeholder="Select Date TO">
            </div>
        </form>
    </div>
</div>
<div class="contentpanel">
    <div class="row-fluid">
        <div id="accordion">
            <?php echo "<h3>Summary</h3>"
            . "<div>" 
            . $this->DataTables(
                $this->result['name'],
                $this->result['header'],
                $this->result['data']
            ) 
            . "</div>"; ?>
        </div>
    </div>
</div>
