<div class="pageheader">
     <div class="media">
         <div class="pageicon pull-left">
             <i class="fa fa-line-chart"></i>
         </div>
         <div class="media-body" style="padding-left: 5px">
             <ul class="breadcrumb">
                 <li>
                     <a href="<?php echo $this->url('mot');?>"><i class="glyphicon glyphicon-home"></i></a>
                 </li>
                 <li> <a href="#">Reports</a></li>
                 <li> <a href="#">Client</a></li>
                 <li>Total Due</li>
             </ul>
             <h4>Client Total Due</h4>
         </div>
     </div>
</div>
<div class="contentpanel">
    <div class="row">
        <?php echo $this->DataTables(['a','b'], ['1','2']); ?>
    </div>
</div>
